### ISSUE TITLE
repo transfer

### ISSUE THREAD

**Issue by jamesturk** [uchicago-mscapp-projects/bus_pending#13]
Hi all, hope you had a nice break and a good start so far to spring quarter.

I am working to consolidate the repositories under https://github.com/uchicago-mscapp-projects

This is of course optional, but if you'd like me to move it, I will either need you to:
- make me an 'admin' on this repository (under settings -> users)
- transfer the repo to 'jamesturk' so I can transfer it from there

Either will work, and no rush.

**Comment by RMedina19** [comment]
Hi, professor! 

Yes, we would love to have our work along with other CAPP projects. 

I'm not sure why, but I did not see the option of granting you admin status; so I just tried to do the repo transfer. I guess you should see and invitation to accept the repo or something of that nature. 

Let me know if this is the case or if I should do something different.

**Comment by jamesturk** [comment]
Thank you! Moved!
